### ISSUE TITLE
Gigya error 403003 when sending requests

### ISSUE THREAD

**Issue by steven-indiloop** [scotthovestadt/node-gigya#1]
When I try to call the servers, using NotifyLogin, I get the error :

403003	Invalid request signature	The request is not signed with a valid signature. Please refer to Signing requests for more details.

I got a response from Gigya, stating:
"
It's likely because the timestamp on the server is off.

Easy solution: when constructing the Gigya object, pass "true" as the 3rd parameter to use HTTPS mode (which doesn't require a signature).

var gigya = new Giga('apiKey', 'secret', true);
"

When I add the 3rd param 'true', as recommended, Gigya behaves properly.

This should, however, work in both configurations, which is what this bug is about.

**Comment by danzaner** [comment]
@steven-indiloop Thank you!!

**Comment by scotthovestadt** [comment]
Usually this error happens when the timestamp on your server is out of sync with Gigya's server. I'll adjust the default to be to use HTTPS.

**Comment by scotthovestadt** [comment]
Done, published to NPM as ````v0.0.10````.
