### ISSUE TITLE
can't use script as a module

### ISSUE THREAD

**Issue by luckpo** [scotthovestadt/node-gigya#4]
Hello
The api client works perfectly when used in a CLI script, but never returns nothing when used as a lib in my app.

Beyond the starting of the request in screenshot, I can't even console.log stuff

Tested on osX and on an EC2 machine.

Could it be due to my configuration ? linux packages missing ? I have received no warnings at all and it works well on a CLI environment

![screen shot 2016-08-01 at 13 52 20](https://cloud.githubusercontent.com/assets/2563787/17294499/36d59764-57ef-11e6-8383-74ec22a450f6.png)

**Comment by luckpo** [comment]
Don't worry about this it was config issues

**Comment by scotthovestadt** [comment]
OK, thanks for letting me know you resolved the issue.
